# Generated by Django 2.0 on 2018-01-02 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BIGIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mgmt_ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='DSC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.AddField(
            model_name='bigip',
            name='dsc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsc.DSC'),
        ),
    ]
