# Generated by Django 2.0 on 2018-01-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dsc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bigip',
            name='login',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bigip',
            name='password',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
