# Generated by Django 2.0.1 on 2018-01-23 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_dsc'),
        ('dsc', '0002_auto_20180105_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrafficGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Application')),
            ],
        ),
        migrations.CreateModel(
            name='VIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField()),
            ],
        ),
        migrations.CreateModel(
            name='VirtualServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='application.Application')),
            ],
        ),
        migrations.AddField(
            model_name='bigip',
            name='device_name',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='bigip',
            name='primary',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='bigip',
            name='dsc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsc.DSC'),
        ),
        migrations.AddField(
            model_name='trafficgroup',
            name='bigips',
            field=models.ManyToManyField(to='dsc.BIGIP'),
        ),
    ]
