# Generated by Django 2.0 on 2018-01-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('protocol', models.IntegerField(choices=[('TCP', 1), ('UDP', 2)])),
                ('socket_port', models.IntegerField()),
            ],
        ),
    ]
