# Generated by Django 2.0.1 on 2018-01-23 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_application_dsc'),
        ('dsc', '0003_auto_20180123_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='vip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dsc.VIP'),
        ),
        migrations.AddField(
            model_name='application',
            name='virtual_server',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AlterField(
            model_name='application',
            name='protocol',
            field=models.IntegerField(choices=[(1, 'TCP'), (2, 'UDP')]),
        ),
    ]
